version: "3.8"

services:
  db:
    image: postgres:16
    container_name: n8n-agent-db
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:16
    container_name: n8n-agent-db-init
    environment:
      PGPASSWORD: n8n
    volumes:
      - ./sql:/sql:ro
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "psql -h db -U n8n -d n8n -f /sql/schema.sql || true"]
    restart: "no"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-agent-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      db:
        condition: service_healthy

  python-svc:
    build:
      context: ./python-svc
    container_name: n8n-agent-python-svc
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql+psycopg2://n8n:n8n@db:5432/n8n
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

volumes:
  n8n_data:
  db_data:
